# CRM Query Engine Test
This notebook demonstrates the implementation and usage of the SQL query engine.

In [1]:
from currensee.schema.schema import PostgresTables
from currensee.query_engines.sql_query_engine.query_engine import create_sql_workflow
from currensee.utils.db_utils import create_pg_engine
from currensee.query_engines.workflow_descriptions import crm_portfolio_table_desc, crm_client_alignment_table_desc,crm_client_info_table_desc, crm_employees_table_desc,crm_fund_details_desc
from currensee.query_engines.workflow_descriptions import outlook_email_table_desc, outlook_meeting_table_desc

In [2]:
# required to run asynchronous code

import nest_asyncio

nest_asyncio.apply()

## Create the SQL Workflow

The SQL workflow can take the following parameters:

1. source_db: the name of the database where the table is stored (e.g. `crm`)
2. source_tables: a list of the name(s) of the table(s) that we want the query engine to have access to
  * note that multiple tables can be passed - this is if you want the query engine to try to join tables
    in the queries that may have relationships to one another
  * THIS IS LEVEL 2!! So do not attempt until you get the hang of just using one table at a time!!
    
3. table_descriptions: a list of the description(s) of the table(s) passed above
4. text_to_sql_tmpl: a string containing the prompt telling the LLM how to produce the SQL query from the text given
   * defaults to the variable `text_to_sql_tmpl` defined in `currensee.query_engines.prompting.py`
   * you may override this by passing in your own string
5. response_synthesis_prompt_str: a string containing the prompt telling the LLM how to synthesize the final response from the SQL table(s)
   * defaults to the variable `response_synthesis_prompt_str` defined in `currensee.query_engines.prompting.py`
   * you may override this by passing in your own string
6. model: the name of the model to use for all of the tasks
   * defaults to `gemini-1.5-flash`
   * you may override this with any of the models defined at https://ai.google.dev/gemini-api/docs/models#model-variations using the string with dashes defined in the "Model variant" column.
   * **BE VERY CAREFUL TO PAY ATTENTION TO THE PRICING!!!!!** I recommend that you use the default model until you understand the other models better!!!
7. temperature: the temperature parameter to pass to the model
   * default is 0.0
   * the higher the temperature, the more creative it is. Recommend keeping low for the SQL query generation.

### Below is the default defined in `prompting.py`

In [3]:
text_to_sql_tmpl = """
    Given an input question, first create a syntactically correct {dialect} query to run, then look at the results of the query and return the answer.
    You can order the results by the find_date column (from earliest to latest) to return the most interesting examples in the database.

    GUIDELINES:
    * Never query for all the columns from a specific table, only ask for a few relevant columns given the question.
    * Pay attention to use only the column names that you can see in the schema description.
    * Be careful to not query for columns that do not exist.
    * Pay attention to which column is in which table.
    * Make sure to filter on all criteria mentioned in the query.
    * If using a LIMIT to restrict the results, make sure it comes only in the end of the query.

    IMPORTANT NOTE:
    * Use the ~* operator instead of = when filtering with WHERE on text columns.
    * Add word boundaries '\y' to the beginning and end of each search term in the query.

    You are required to use the following format, each taking one line:

    Question: Question here
    SQLQuery: SQL Query to run
    SQLResult: Result of the SQLQuery
    Answer: Final answer here

    Only use tables listed below.
    {schema}

    Question: {query_str}
    SQLQuery:

"""

### Below is the default defined in `prompting.py`

In [4]:
response_synthesis_prompt_str = """

    Query: {query_str}
    SQL: {sql_query}
    SQL Response: {context_str}

    IMPORTANT INSTRUCTIONS:
    * If SQL Response is empty or 0, apologise and mention that you could not find
     examples to answer the query.
    * In such cases, kindly nudge the user towards providing more details or refining
    their search.
    * Additionally, you can tell them to rephrase specific keywords.
    * Do not explicitly state phrases such as 'based on the SQL query executed' or related
     references to context in your Response.
    * Never mention the underlying sql query, or the underling sql tables and other database elements
    * Never mention that sql was used to answer this question

    Considering the IMPORTANT INSTRUCTIONS above, create an response using the information
    returned from the database and no prior knowledge.


    Response:
"""

### Define the DB information
**IMPORTANT**: The table names MUST be lowercase in order for the engine to find them.

In [10]:
source_db = 'crm'
table_description_mapping = {
    'employees': crm_employees_table_desc,
    'portfolio': crm_portfolio_table_desc,
    'fund_detail': crm_fund_details_desc,
    'client_alignment': crm_client_alignment_table_desc,
    'clients_contact': crm_client_info_table_desc
}

In [11]:
sql_workflow = create_sql_workflow(
    source_db = source_db,
    table_description_mapping=table_description_mapping,
    text_to_sql_tmpl=text_to_sql_tmpl,
    response_synthesis_prompt_str=response_synthesis_prompt_str
)

# Test Queries

In [12]:
query = "Who works for bankwell?"
result = await sql_workflow.run(query=query)
result

Running step generate_sql_response
Step generate_sql_response produced event StopEvent

Response(response='The following individuals work at Bankwell: Jane Moneypenny, Daniel Brown, Gary Jackson, Margaret Moreno, Vicki Garner, Thomas Townsend, Paul Jennings, Deanna Baker, Jennifer Dawson, Lisa Johnson, Alexander Zavala, Christopher Young, Caleb Montgomery, John Hall, Michele Benson, Tanya Harris, Kelly Herrera, James Smith, Eric Parks, James Gordon, Lisa Bridges, Jessica Moss, Maria Mitchell, Derek Ayers, Sean Kelly, David Bishop, John Medina, David Barton, Ashlee Torres, Ronald Goodwin, Joseph Nelson, Michael Mercer, Traci Jacobs, Carol Clarke, Debra Mendoza, James Rice, Marie Stewart, Jennifer Richmond, Nicholas Perez, Alexandra Joseph, Derek Brown, Amanda Henry, Brenda Martinez, Donna Pruitt, Paul Baker, Karen Clayton, Derrick Johnson, Janice Jones, Wesley Hoover, Frances Ramirez, Gail Rogers, Derek Taylor, Michael Perez, Jon Stanley, Kathy Howard, Sandra Gallagher, Seth Frye, Victoria Ross, Shelby Davis, Ryan Barnett, Christopher Taylor, Justin Rios, Jeffrey Brooks, Jesse Sanchez, Johnny Cook, Victoria Hinton, Teresa Buchanan, Cindy Jimenez, Jeffrey Arroyo, Ashley Johnston, Mallory Pratt, Clinton Johnson, Carol Kelley, Michael Dickson, Dustin Sanders, Ryan Jackson, James Lutz, Ann Jones, Anthony Acosta, Sara Pennington, Harold Thomas, Carol West, Joshua Keith, Anthony Mason, Mitchell Snyder, Michael Hayes, Lee Weiss, Thomas Allen, Eric Graves, John Miller, Brooke Watkins, John Ford, Chad Jordan, Laura Larsen, Timothy Martinez, Laura Quinn, Justin Green, James Hernandez, and Lisa Duran, Kurt Sanchez.\n', source_nodes=[NodeWithScore(node=TextNode(id_='19fd2640-7c3b-40d4-a346-b7b54cb4b2aa', embedding=None, metadata={'sql_query': 'SELECT first_name, last_name FROM employees;', 'result': [('Jane', 'Moneypenny'), ('Daniel', 'Brown'), ('Gary', 'Jackson'), ('Margaret', 'Moreno'), ('Vicki', 'Garner'), ('Thomas', 'Townsend'), ('Paul', 'Jennings'), ('Deanna', 'Baker'), ('Jennifer', 'Dawson'), ('Lisa', 'Johnson'), ('Alexander', 'Zavala'), ('Christopher', 'Young'), ('Caleb', 'Montgomery'), ('John', 'Hall'), ('Michele', 'Benson'), ('Tanya', 'Harris'), ('Kelly', 'Herrera'), ('James', 'Smith'), ('Eric', 'Parks'), ('James', 'Gordon'), ('Lisa', 'Bridges'), ('Jessica', 'Moss'), ('Maria', 'Mitchell'), ('Derek', 'Ayers'), ('Sean', 'Kelly'), ('David', 'Bishop'), ('John', 'Medina'), ('David', 'Barton'), ('Ashlee', 'Torres'), ('Ronald', 'Goodwin'), ('Joseph', 'Nelson'), ('Michael', 'Mercer'), ('Traci', 'Jacobs'), ('Carol', 'Clarke'), ('Debra', 'Mendoza'), ('James', 'Rice'), ('Marie', 'Stewart'), ('Jennifer', 'Richmond'), ('Nicholas', 'Perez'), ('Alexandra', 'Joseph'), ('Derek', 'Brown'), ('Amanda', 'Henry'), ('Brenda', 'Martinez'), ('Donna', 'Pruitt'), ('Paul', 'Baker'), ('Karen', 'Clayton'), ('Derrick', 'Johnson'), ('Janice', 'Jones'), ('Wesley', 'Hoover'), ('Frances', 'Ramirez'), ('Gail', 'Rogers'), ('Derek', 'Taylor'), ('Michael', 'Perez'), ('Jon', 'Stanley'), ('Kathy', 'Howard'), ('Sandra', 'Gallagher'), ('Seth', 'Frye'), ('Victoria', 'Ross'), ('Shelby', 'Davis'), ('Ryan', 'Barnett'), ('Christopher', 'Taylor'), ('Justin', 'Rios'), ('Jeffrey', 'Brooks'), ('Jesse', 'Sanchez'), ('Johnny', 'Cook'), ('Victoria', 'Hinton'), ('Teresa', 'Buchanan'), ('Cindy', 'Jimenez'), ('Jeffrey', 'Arroyo'), ('Ashley', 'Johnston'), ('Mallory', 'Pratt'), ('Clinton', 'Johnson'), ('Carol', 'Kelley'), ('Michael', 'Dickson'), ('Dustin', 'Sanders'), ('Ryan', 'Jackson'), ('James', 'Lutz'), ('Ann', 'Jones'), ('Anthony', 'Acosta'), ('Sara', 'Pennington'), ('Harold', 'Thomas'), ('Carol', 'West'), ('Joshua', 'Keith'), ('Anthony', 'Mason'), ('Mitchell', 'Snyder'), ('Michael', 'Hayes'), ('Lee', 'Weiss'), ('Thomas', 'Allen'), ('Eric', 'Graves'), ('John', 'Miller'), ('Brooke', 'Watkins'), ('John', 'Ford'), ('Chad', 'Jordan'), ('Laura', 'Larsen'), ('Timothy', 'Martinez'), ('Laura', 'Quinn'), ('Justin', 'Green'), ('James', 'Hernandez'), ('Lisa', 'Duran'), ('Kurt', 'Sanchez')], 'col_keys': ['first_name', 'last_name']}, excluded_embed_metadata_keys=['sql_query', 'result', 'col_keys'], excluded_llm_metadata_keys=['sql_query', 'result', 'col_keys'], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text="[('Jane', 'Moneypenny'), ('Daniel', 'Brown'), ('Gary', 'Jackson'), ('Margaret', 'Moreno'), ('Vicki', 'Garner'), ('Thomas', 'Townsend'), ('Paul', 'Jennings'), ('Deanna', 'Baker'), ('Jennifer', 'Dawson'), ('Lisa', 'Johnson'), ('Alexander', 'Zavala'), ('Christopher', 'Young'), ('Caleb', 'Montgomery'), ('John', 'Hall'), ('Michele', 'Benson'), ('Tanya', 'Harris'), ('Kelly', 'Herrera'), ('James', 'Smith'), ('Eric', 'Parks'), ('James', 'Gordon'), ('Lisa', 'Bridges'), ('Jessica', 'Moss'), ('Maria', 'Mitchell'), ('Derek', 'Ayers'), ('Sean', 'Kelly'), ('David', 'Bishop'), ('John', 'Medina'), ('David', 'Barton'), ('Ashlee', 'Torres'), ('Ronald', 'Goodwin'), ('Joseph', 'Nelson'), ('Michael', 'Mercer'), ('Traci', 'Jacobs'), ('Carol', 'Clarke'), ('Debra', 'Mendoza'), ('James', 'Rice'), ('Marie', 'Stewart'), ('Jennifer', 'Richmond'), ('Nicholas', 'Perez'), ('Alexandra', 'Joseph'), ('Derek', 'Brown'), ('Amanda', 'Henry'), ('Brenda', 'Martinez'), ('Donna', 'Pruitt'), ('Paul', 'Baker'), ('Karen', 'Clayton'), ('Derrick', 'Johnson'), ('Janice', 'Jones'), ('Wesley', 'Hoover'), ('Frances', 'Ramirez'), ('Gail', 'Rogers'), ('Derek', 'Taylor'), ('Michael', 'Perez'), ('Jon', 'Stanley'), ('Kathy', 'Howard'), ('Sandra', 'Gallagher'), ('Seth', 'Frye'), ('Victoria', 'Ross'), ('Shelby', 'Davis'), ('Ryan', 'Barnett'), ('Christopher', 'Taylor'), ('Justin', 'Rios'), ('Jeffrey', 'Brooks'), ('Jesse', 'Sanchez'), ('Johnny', 'Cook'), ('Victoria', 'Hinton'), ('Teresa', 'Buchanan'), ('Cindy', 'Jimenez'), ('Jeffrey', 'Arroyo'), ('Ashley', 'Johnston'), ('Mallory', 'Pratt'), ('Clinton', 'Johnson'), ('Carol', 'Kelley'), ('Michael', 'Dickson'), ('Dustin', 'Sanders'), ('Ryan', 'Jackson'), ('James', 'Lutz'), ('Ann', 'Jones'), ('Anthony', 'Acosta'), ('Sara', 'Pennington'), ('Harold', 'Thomas'), ('Carol', 'West'), ('Joshua', 'Keith'), ('Anthony', 'Mason'), ('Mitchell', 'Snyder'), ('Michael', 'Hayes'), ('Lee', 'Weiss'), ('Thomas', 'Allen'), ('Eric', 'Graves'), ('John', 'Miller'), ('Brooke', 'Watkins'), ('John', 'Ford'), ('Chad', 'Jordan'), ('Laura', 'Larsen'), ('Timothy', 'Martinez'), ('Laura', 'Quinn'), ('Justin', 'Green'), ('James', 'Hernandez'), ('Lisa', 'Duran'), ('Kurt', 'Sanchez')]", mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=None)], metadata={'19fd2640-7c3b-40d4-a346-b7b54cb4b2aa': {'sql_query': 'SELECT first_name, last_name FROM employees;', 'result': [('Jane', 'Moneypenny'), ('Daniel', 'Brown'), ('Gary', 'Jackson'), ('Margaret', 'Moreno'), ('Vicki', 'Garner'), ('Thomas', 'Townsend'), ('Paul', 'Jennings'), ('Deanna', 'Baker'), ('Jennifer', 'Dawson'), ('Lisa', 'Johnson'), ('Alexander', 'Zavala'), ('Christopher', 'Young'), ('Caleb', 'Montgomery'), ('John', 'Hall'), ('Michele', 'Benson'), ('Tanya', 'Harris'), ('Kelly', 'Herrera'), ('James', 'Smith'), ('Eric', 'Parks'), ('James', 'Gordon'), ('Lisa', 'Bridges'), ('Jessica', 'Moss'), ('Maria', 'Mitchell'), ('Derek', 'Ayers'), ('Sean', 'Kelly'), ('David', 'Bishop'), ('John', 'Medina'), ('David', 'Barton'), ('Ashlee', 'Torres'), ('Ronald', 'Goodwin'), ('Joseph', 'Nelson'), ('Michael', 'Mercer'), ('Traci', 'Jacobs'), ('Carol', 'Clarke'), ('Debra', 'Mendoza'), ('James', 'Rice'), ('Marie', 'Stewart'), ('Jennifer', 'Richmond'), ('Nicholas', 'Perez'), ('Alexandra', 'Joseph'), ('Derek', 'Brown'), ('Amanda', 'Henry'), ('Brenda', 'Martinez'), ('Donna', 'Pruitt'), ('Paul', 'Baker'), ('Karen', 'Clayton'), ('Derrick', 'Johnson'), ('Janice', 'Jones'), ('Wesley', 'Hoover'), ('Frances', 'Ramirez'), ('Gail', 'Rogers'), ('Derek', 'Taylor'), ('Michael', 'Perez'), ('Jon', 'Stanley'), ('Kathy', 'Howard'), ('Sandra', 'Gallagher'), ('Seth', 'Frye'), ('Victoria', 'Ross'), ('Shelby', 'Davis'), ('Ryan', 'Barnett'), ('Christopher', 'Taylor'), ('Justin', 'Rios'), ('Jeffrey', 'Brooks'), ('Jesse', 'Sanchez'), ('Johnny', 'Cook'), ('Victoria', 'Hinton'), ('Teresa', 'Buchanan'), ('Cindy', 'Jimenez'), ('Jeffrey', 'Arroyo'), ('Ashley', 'Johnston'), ('Mallory', 'Pratt'), ('Clinton', 'Johnson'), ('Carol', 'Kelley'), ('Michael', 'Dickson'), ('Dustin', 'Sanders'), ('Ryan', 'Jackson'), ('James', 'Lutz'), ('Ann', 'Jones'), ('Anthony', 'Acosta'), ('Sara', 'Pennington'), ('Harold', 'Thomas'), ('Carol', 'West'), ('Joshua', 'Keith'), ('Anthony', 'Mason'), ('Mitchell', 'Snyder'), ('Michael', 'Hayes'), ('Lee', 'Weiss'), ('Thomas', 'Allen'), ('Eric', 'Graves'), ('John', 'Miller'), ('Brooke', 'Watkins'), ('John', 'Ford'), ('Chad', 'Jordan'), ('Laura', 'Larsen'), ('Timothy', 'Martinez'), ('Laura', 'Quinn'), ('Justin', 'Green'), ('James', 'Hernandez'), ('Lisa', 'Duran'), ('Kurt', 'Sanchez')], 'col_keys': ['first_name', 'last_name']}, 'sql_query': 'SELECT first_name, last_name FROM employees;', 'result': [('Jane', 'Moneypenny'), ('Daniel', 'Brown'), ('Gary', 'Jackson'), ('Margaret', 'Moreno'), ('Vicki', 'Garner'), ('Thomas', 'Townsend'), ('Paul', 'Jennings'), ('Deanna', 'Baker'), ('Jennifer', 'Dawson'), ('Lisa', 'Johnson'), ('Alexander', 'Zavala'), ('Christopher', 'Young'), ('Caleb', 'Montgomery'), ('John', 'Hall'), ('Michele', 'Benson'), ('Tanya', 'Harris'), ('Kelly', 'Herrera'), ('James', 'Smith'), ('Eric', 'Parks'), ('James', 'Gordon'), ('Lisa', 'Bridges'), ('Jessica', 'Moss'), ('Maria', 'Mitchell'), ('Derek', 'Ayers'), ('Sean', 'Kelly'), ('David', 'Bishop'), ('John', 'Medina'), ('David', 'Barton'), ('Ashlee', 'Torres'), ('Ronald', 'Goodwin'), ('Joseph', 'Nelson'), ('Michael', 'Mercer'), ('Traci', 'Jacobs'), ('Carol', 'Clarke'), ('Debra', 'Mendoza'), ('James', 'Rice'), ('Marie', 'Stewart'), ('Jennifer', 'Richmond'), ('Nicholas', 'Perez'), ('Alexandra', 'Joseph'), ('Derek', 'Brown'), ('Amanda', 'Henry'), ('Brenda', 'Martinez'), ('Donna', 'Pruitt'), ('Paul', 'Baker'), ('Karen', 'Clayton'), ('Derrick', 'Johnson'), ('Janice', 'Jones'), ('Wesley', 'Hoover'), ('Frances', 'Ramirez'), ('Gail', 'Rogers'), ('Derek', 'Taylor'), ('Michael', 'Perez'), ('Jon', 'Stanley'), ('Kathy', 'Howard'), ('Sandra', 'Gallagher'), ('Seth', 'Frye'), ('Victoria', 'Ross'), ('Shelby', 'Davis'), ('Ryan', 'Barnett'), ('Christopher', 'Taylor'), ('Justin', 'Rios'), ('Jeffrey', 'Brooks'), ('Jesse', 'Sanchez'), ('Johnny', 'Cook'), ('Victoria', 'Hinton'), ('Teresa', 'Buchanan'), ('Cindy', 'Jimenez'), ('Jeffrey', 'Arroyo'), ('Ashley', 'Johnston'), ('Mallory', 'Pratt'), ('Clinton', 'Johnson'), ('Carol', 'Kelley'), ('Michael', 'Dickson'), ('Dustin', 'Sanders'), ('Ryan', 'Jackson'), ('James', 'Lutz'), ('Ann', 'Jones'), ('Anthony', 'Acosta'), ('Sara', 'Pennington'), ('Harold', 'Thomas'), ('Carol', 'West'), ('Joshua', 'Keith'), ('Anthony', 'Mason'), ('Mitchell', 'Snyder'), ('Michael', 'Hayes'), ('Lee', 'Weiss'), ('Thomas', 'Allen'), ('Eric', 'Graves'), ('John', 'Miller'), ('Brooke', 'Watkins'), ('John', 'Ford'), ('Chad', 'Jordan'), ('Laura', 'Larsen'), ('Timothy', 'Martinez'), ('Laura', 'Quinn'), ('Justin', 'Green'), ('James', 'Hernandez'), ('Lisa', 'Duran'), ('Kurt', 'Sanchez')], 'col_keys': ['first_name', 'last_name'], 'user_query': 'Who works for bankwell?'})

In [13]:
query = "How many people work for bankwell in the Sales department?"
result = await sql_workflow.run(query=query)
result

Running step generate_sql_response
Step generate_sql_response produced event StopEvent

Response(response='There are 23 people working in the Sales department at Bankwell.\n', source_nodes=[NodeWithScore(node=TextNode(id_='f6466eca-7354-42fa-b95b-d22ee1f55354', embedding=None, metadata={'sql_query': "SELECT count(*) FROM employees WHERE department ~* '\\ySales\\y';", 'result': [(23,)], 'col_keys': ['count']}, excluded_embed_metadata_keys=['sql_query', 'result', 'col_keys'], excluded_llm_metadata_keys=['sql_query', 'result', 'col_keys'], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='[(23,)]', mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=None)], metadata={'f6466eca-7354-42fa-b95b-d22ee1f55354': {'sql_query': "SELECT count(*) FROM employees WHERE department ~* '\\ySales\\y';", 'result': [(23,)], 'col_keys': ['count']}, 'sql_query': "SELECT count(*) FROM employees WHERE department ~* '\\ySales\\y';", 'result': [(23,)], 'col_keys': ['count'], 'user_query': 'How many people work for bankwell in the Sales department?'})

In [14]:
query = "what financial instruments does Mariott own?"
result = await sql_workflow.run(query=query)
result

Running step generate_sql_response
Step generate_sql_response produced event StopEvent

Response(response="Marriott appears to hold investments in VSMPX and BND.  To get a more complete picture of Marriott's financial instruments, you might want to try refining your search or providing additional details.\n", source_nodes=[NodeWithScore(node=TextNode(id_='78f8f773-4d71-4a20-bcb0-ae8df8a8e1db', embedding=None, metadata={'sql_query': "SELECT symbol FROM portfolio WHERE company ~* '\\yMariott\\y'", 'result': [('VSMPX',), ('BND',)], 'col_keys': ['symbol']}, excluded_embed_metadata_keys=['sql_query', 'result', 'col_keys'], excluded_llm_metadata_keys=['sql_query', 'result', 'col_keys'], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text="[('VSMPX',), ('BND',)]", mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=None)], metadata={'78f8f773-4d71-4a20-bcb0-ae8df8a8e1db': {'sql_query': "SELECT symbol FROM portfolio WHERE company ~* '\\yMariott\\y'", 'result': [('VSMPX',), ('BND',)], 'col_keys': ['symbol']}, 'sql_query': "SELECT symbol FROM portfolio WHERE company ~* '\\yMariott\\y'", 'result': [('VSMPX',), ('BND',)], 'col_keys': ['symbol'], 'user_query': 'what financial instruments does Mariott own?'})

In [15]:
query = "how many funds does Broadcom own? What types of funds are they?"
result = await sql_workflow.run(query=query)
result

Running step generate_sql_response
Step generate_sql_response produced event StopEvent

Response(response='Broadcom owns 5 funds.  These funds are categorized as Bond Funds and Equity Funds.\n', source_nodes=[NodeWithScore(node=TextNode(id_='2caa1712-b070-4bf5-b5e8-4dd67a4507d0', embedding=None, metadata={'sql_query': "SELECT COUNT(*) AS num_funds, array_agg(DISTINCT fund_type) AS fund_types FROM portfolio WHERE company ~* '\\yBroadcom\\y';", 'result': [(5, ['Bond Fund', 'Equity Fund'])], 'col_keys': ['num_funds', 'fund_types']}, excluded_embed_metadata_keys=['sql_query', 'result', 'col_keys'], excluded_llm_metadata_keys=['sql_query', 'result', 'col_keys'], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text="[(5, ['Bond Fund', 'Equity Fund'])]", mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=None)], metadata={'2caa1712-b070-4bf5-b5e8-4dd67a4507d0': {'sql_query': "SELECT COUNT(*) AS num_funds, array_agg(DISTINCT fund_type) AS fund_types FROM portfolio WHERE company ~* '\\yBroadcom\\y';", 'result': [(5, ['Bond Fund', 'Equity Fund'])], 'col_keys': ['num_funds', 'fund_types']}, 'sql_query': "SELECT COUNT(*) AS num_funds, array_agg(DISTINCT fund_type) AS fund_types FROM portfolio WHERE company ~* '\\yBroadcom\\y';", 'result': [(5, ['Bond Fund', 'Equity Fund'])], 'col_keys': ['num_funds', 'fund_types'], 'user_query': 'how many funds does Broadcom own? What types of funds are they?'})

In [16]:
query = "What is Broadcom's total balance? What fund does broadcom have the most money in, and how much is there?"
result = await sql_workflow.run(query=query)
result

Running step generate_sql_response
Step generate_sql_response produced event StopEvent

Response(response="Broadcom's total balance is $43,751,152.  The fund holding the most money for Broadcom is FXAIX, with a balance of $14,499,284.22.\n", source_nodes=[NodeWithScore(node=TextNode(id_='c0c79906-4bbe-4995-94ea-dc9c638065f5', embedding=None, metadata={'sql_query': "SELECT T1.tot_balance, T1.symbol, T1.fund_balance FROM portfolio AS T1 WHERE T1.company ~* '\\yBroadcom\\y' ORDER BY T1.fund_balance DESC LIMIT 1;", 'result': [(43751152, 'FXAIX', 14499284.22)], 'col_keys': ['tot_balance', 'symbol', 'fund_balance']}, excluded_embed_metadata_keys=['sql_query', 'result', 'col_keys'], excluded_llm_metadata_keys=['sql_query', 'result', 'col_keys'], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text="[(43751152, 'FXAIX', 14499284.22)]", mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=None)], metadata={'c0c79906-4bbe-4995-94ea-dc9c638065f5': {'sql_query': "SELECT T1.tot_balance, T1.symbol, T1.fund_balance FROM portfolio AS T1 WHERE T1.company ~* '\\yBroadcom\\y' ORDER BY T1.fund_balance DESC LIMIT 1;", 'result': [(43751152, 'FXAIX', 14499284.22)], 'col_keys': ['tot_balance', 'symbol', 'fund_balance']}, 'sql_query': "SELECT T1.tot_balance, T1.symbol, T1.fund_balance FROM portfolio AS T1 WHERE T1.company ~* '\\yBroadcom\\y' ORDER BY T1.fund_balance DESC LIMIT 1;", 'result': [(43751152, 'FXAIX', 14499284.22)], 'col_keys': ['tot_balance', 'symbol', 'fund_balance'], 'user_query': "What is Broadcom's total balance? What fund does broadcom have the most money in, and how much is there?"})

In [17]:
query = "How much money does broadcom have in each fund?"
result = await sql_workflow.run(query=query)
result

Running step generate_sql_response
Step generate_sql_response produced event StopEvent

Response(response='Broadcom has $12,166,681.60 in the Bond Fund and $31,584,470.40 in the Equity Fund.\n', source_nodes=[NodeWithScore(node=TextNode(id_='219b7130-30d7-4cdb-8189-b3c4972da629', embedding=None, metadata={'sql_query': "SELECT fund_type, SUM(fund_balance) FROM portfolio WHERE company ~* '\\ybroadcom\\y' GROUP BY fund_type;", 'result': [('Bond Fund', 12166681.6), ('Equity Fund', 31584470.4)], 'col_keys': ['fund_type', 'sum']}, excluded_embed_metadata_keys=['sql_query', 'result', 'col_keys'], excluded_llm_metadata_keys=['sql_query', 'result', 'col_keys'], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text="[('Bond Fund', 12166681.6), ('Equity Fund', 31584470.4)]", mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=None)], metadata={'219b7130-30d7-4cdb-8189-b3c4972da629': {'sql_query': "SELECT fund_type, SUM(fund_balance) FROM portfolio WHERE company ~* '\\ybroadcom\\y' GROUP BY fund_type;", 'result': [('Bond Fund', 12166681.6), ('Equity Fund', 31584470.4)], 'col_keys': ['fund_type', 'sum']}, 'sql_query': "SELECT fund_type, SUM(fund_balance) FROM portfolio WHERE company ~* '\\ybroadcom\\y' GROUP BY fund_type;", 'result': [('Bond Fund', 12166681.6), ('Equity Fund', 31584470.4)], 'col_keys': ['fund_type', 'sum'], 'user_query': 'How much money does broadcom have in each fund?'})

In [18]:
query = "what employees work on the mariott client account?"
result = await sql_workflow.run(query=query)
result

Running step generate_sql_response
Step generate_sql_response produced event StopEvent

Response(response='The following employees work on the Marriott client account: Gary Jackson, Vicki Garner, Caleb Montgomery, James Gordon, Lisa Bridges, Ashlee Torres, Traci Jacobs, Debra Mendoza, Jennifer Richmond, Donna Pruitt, Derek Taylor, Michael Perez, Jon Stanley, Ryan Barnett, Carol Kelley, Eric Graves, and John Miller.\n', source_nodes=[NodeWithScore(node=TextNode(id_='0f7b210d-7f47-4244-8c52-43926a6cc6c5', embedding=None, metadata={'sql_query': "SELECT employee_first_name, employee_last_name FROM client_alignment WHERE company ~* '\\ymariott\\y'", 'result': [('Gary', 'Jackson'), ('Vicki', 'Garner'), ('Caleb', 'Montgomery'), ('James', 'Gordon'), ('Lisa', 'Bridges'), ('Ashlee', 'Torres'), ('Traci', 'Jacobs'), ('Debra', 'Mendoza'), ('Jennifer', 'Richmond'), ('Donna', 'Pruitt'), ('Derek', 'Taylor'), ('Michael', 'Perez'), ('Jon', 'Stanley'), ('Ryan', 'Barnett'), ('Carol', 'Kelley'), ('Eric', 'Graves'), ('John', 'Miller')], 'col_keys': ['employee_first_name', 'employee_last_name']}, excluded_embed_metadata_keys=['sql_query', 'result', 'col_keys'], excluded_llm_metadata_keys=['sql_query', 'result', 'col_keys'], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text="[('Gary', 'Jackson'), ('Vicki', 'Garner'), ('Caleb', 'Montgomery'), ('James', 'Gordon'), ('Lisa', 'Bridges'), ('Ashlee', 'Torres'), ('Traci', 'Jacobs'), ('Debra', 'Mendoza'), ('Jennifer', 'Richmond'), ('Donna', 'Pruitt'), ('Derek', 'Taylor'), ('Michael', 'Perez'), ('Jon', 'Stanley'), ('Ryan', 'Barnett'), ('Carol', 'Kelley'), ('Eric', 'Graves'), ('John', 'Miller')]", mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=None)], metadata={'0f7b210d-7f47-4244-8c52-43926a6cc6c5': {'sql_query': "SELECT employee_first_name, employee_last_name FROM client_alignment WHERE company ~* '\\ymariott\\y'", 'result': [('Gary', 'Jackson'), ('Vicki', 'Garner'), ('Caleb', 'Montgomery'), ('James', 'Gordon'), ('Lisa', 'Bridges'), ('Ashlee', 'Torres'), ('Traci', 'Jacobs'), ('Debra', 'Mendoza'), ('Jennifer', 'Richmond'), ('Donna', 'Pruitt'), ('Derek', 'Taylor'), ('Michael', 'Perez'), ('Jon', 'Stanley'), ('Ryan', 'Barnett'), ('Carol', 'Kelley'), ('Eric', 'Graves'), ('John', 'Miller')], 'col_keys': ['employee_first_name', 'employee_last_name']}, 'sql_query': "SELECT employee_first_name, employee_last_name FROM client_alignment WHERE company ~* '\\ymariott\\y'", 'result': [('Gary', 'Jackson'), ('Vicki', 'Garner'), ('Caleb', 'Montgomery'), ('James', 'Gordon'), ('Lisa', 'Bridges'), ('Ashlee', 'Torres'), ('Traci', 'Jacobs'), ('Debra', 'Mendoza'), ('Jennifer', 'Richmond'), ('Donna', 'Pruitt'), ('Derek', 'Taylor'), ('Michael', 'Perez'), ('Jon', 'Stanley'), ('Ryan', 'Barnett'), ('Carol', 'Kelley'), ('Eric', 'Graves'), ('John', 'Miller')], 'col_keys': ['employee_first_name', 'employee_last_name'], 'user_query': 'what employees work on the mariott client account?'})

In [19]:
query = "what is the client email for Mariott?"
result = await sql_workflow.run(query=query)
result

Running step generate_sql_response
Step generate_sql_response produced event StopEvent

Response(response='The email address for Marriott is christian.scott@mariott.com.\n', source_nodes=[NodeWithScore(node=TextNode(id_='0cc0e8b6-75f0-466e-a5f9-991291808cc9', embedding=None, metadata={'sql_query': "SELECT email FROM clients_contact WHERE company ~* '\\yMariott\\y'", 'result': [('christian.scott@mariott.com',)], 'col_keys': ['email']}, excluded_embed_metadata_keys=['sql_query', 'result', 'col_keys'], excluded_llm_metadata_keys=['sql_query', 'result', 'col_keys'], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text="[('christian.scott@mariott.com',)]", mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=None)], metadata={'0cc0e8b6-75f0-466e-a5f9-991291808cc9': {'sql_query': "SELECT email FROM clients_contact WHERE company ~* '\\yMariott\\y'", 'result': [('christian.scott@mariott.com',)], 'col_keys': ['email']}, 'sql_query': "SELECT email FROM clients_contact WHERE company ~* '\\yMariott\\y'", 'result': [('christian.scott@mariott.com',)], 'col_keys': ['email'], 'user_query': 'what is the client email for Mariott?'})

In [20]:
query = "what is the stocks does the client Broadcom have in their funds?"
result = await sql_workflow.run(query=query)
result

Running step generate_sql_response
Step generate_sql_response produced event StopEvent

Response(response='The following stocks are held in funds associated with Broadcom: NVIDIA Corp, Apple Inc, Amazon.com Inc, Microsoft Corp, Meta Platforms Inc, Berkshire Hathaway Inc, Tesla A, Walmart Inc, Exxon Mobil Corp, Intel Corp, Netflix Inc, Eli Lilly & co, Amphenol Corp, Alphabet Inc Class A, AT&T Inc, Bank of America Corp, Fannie Mae Pool, Ginnie Mae II Pool, and Freddie Mac.  Note that some stocks appear multiple times in the list.\n', source_nodes=[NodeWithScore(node=TextNode(id_='58ec050e-498f-4e37-a2dc-aa6b64ead9ed', embedding=None, metadata={'sql_query': "SELECT T1.position_name FROM fund_detail AS T1 INNER JOIN portfolio AS T2 ON T1.fund  =  T2.symbol WHERE T2.company ~* '\\yBroadcom\\y'", 'result': [('NVDIA Corp',), ('Apple Inc',), ('Amazon.com Inc',), ('Microsoft Corp',), ('Meta Platforms Inc',), ('Berkshire Hathaway Inc',), ('Tesla A',), ('Walmart Inc',), ('Exxon Mobil Corp',), ('Intel Corp',), ('NVDIA Corp',), ('Apple Inc',), ('Amazon.com Inc',), ('Microsoft Corp',), ('Meta Platforms Inc',), ('Berkshire Hathaway Inc',), ('Netflix Inc',), ('Eli Lilly & co',), ('Amphenol Corp',), ('Alphabet Inc Class A',), ('NVDIA Corp',), ('Apple Inc',), ('Amazon.com Inc',), ('Microsoft Corp',), ('AT&T Inc',), ('Bank fo America Corp',), ('Alphabet Inc Class A',), ('Walmart Inc',), ('Exxon Mobil Corp',), ('Intel Corp',), ('Fannie Mae Pool',), ('Ginnie Mae II Pool',), ('Freddie Mac',), ('Fannie Mae Pool',), ('Ginnie Mae II Pool',), ('Freddie Mac',)], 'col_keys': ['position_name']}, excluded_embed_metadata_keys=['sql_query', 'result', 'col_keys'], excluded_llm_metadata_keys=['sql_query', 'result', 'col_keys'], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text="[('NVDIA Corp',), ('Apple Inc',), ('Amazon.com Inc',), ('Microsoft Corp',), ('Meta Platforms Inc',), ('Berkshire Hathaway Inc',), ('Tesla A',), ('Walmart Inc',), ('Exxon Mobil Corp',), ('Intel Corp',), ('NVDIA Corp',), ('Apple Inc',), ('Amazon.com Inc',), ('Microsoft Corp',), ('Meta Platforms Inc',), ('Berkshire Hathaway Inc',), ('Netflix Inc',), ('Eli Lilly & co',), ('Amphenol Corp',), ('Alphabet Inc Class A',), ('NVDIA Corp',), ('Apple Inc',), ('Amazon.com Inc',), ('Microsoft Corp',), ('AT&T Inc',), ('Bank fo America Corp',), ('Alphabet Inc Class A',), ('Walmart Inc',), ('Exxon Mobil Corp',), ('Intel Corp',), ('Fannie Mae Pool',), ('Ginnie Mae II Pool',), ('Freddie Mac',), ('Fannie Mae Pool',), ('Ginnie Mae II Pool',), ('Freddie Mac',)]", mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=None)], metadata={'58ec050e-498f-4e37-a2dc-aa6b64ead9ed': {'sql_query': "SELECT T1.position_name FROM fund_detail AS T1 INNER JOIN portfolio AS T2 ON T1.fund  =  T2.symbol WHERE T2.company ~* '\\yBroadcom\\y'", 'result': [('NVDIA Corp',), ('Apple Inc',), ('Amazon.com Inc',), ('Microsoft Corp',), ('Meta Platforms Inc',), ('Berkshire Hathaway Inc',), ('Tesla A',), ('Walmart Inc',), ('Exxon Mobil Corp',), ('Intel Corp',), ('NVDIA Corp',), ('Apple Inc',), ('Amazon.com Inc',), ('Microsoft Corp',), ('Meta Platforms Inc',), ('Berkshire Hathaway Inc',), ('Netflix Inc',), ('Eli Lilly & co',), ('Amphenol Corp',), ('Alphabet Inc Class A',), ('NVDIA Corp',), ('Apple Inc',), ('Amazon.com Inc',), ('Microsoft Corp',), ('AT&T Inc',), ('Bank fo America Corp',), ('Alphabet Inc Class A',), ('Walmart Inc',), ('Exxon Mobil Corp',), ('Intel Corp',), ('Fannie Mae Pool',), ('Ginnie Mae II Pool',), ('Freddie Mac',), ('Fannie Mae Pool',), ('Ginnie Mae II Pool',), ('Freddie Mac',)], 'col_keys': ['position_name']}, 'sql_query': "SELECT T1.position_name FROM fund_detail AS T1 INNER JOIN portfolio AS T2 ON T1.fund  =  T2.symbol WHERE T2.company ~* '\\yBroadcom\\y'", 'result': [('NVDIA Corp',), ('Apple Inc',), ('Amazon.com Inc',), ('Microsoft Corp',), ('Meta Platforms Inc',), ('Berkshire Hathaway Inc',), ('Tesla A',), ('Walmart Inc',), ('Exxon Mobil Corp',), ('Intel Corp',), ('NVDIA Corp',), ('Apple Inc',), ('Amazon.com Inc',), ('Microsoft Corp',), ('Meta Platforms Inc',), ('Berkshire Hathaway Inc',), ('Netflix Inc',), ('Eli Lilly & co',), ('Amphenol Corp',), ('Alphabet Inc Class A',), ('NVDIA Corp',), ('Apple Inc',), ('Amazon.com Inc',), ('Microsoft Corp',), ('AT&T Inc',), ('Bank fo America Corp',), ('Alphabet Inc Class A',), ('Walmart Inc',), ('Exxon Mobil Corp',), ('Intel Corp',), ('Fannie Mae Pool',), ('Ginnie Mae II Pool',), ('Freddie Mac',), ('Fannie Mae Pool',), ('Ginnie Mae II Pool',), ('Freddie Mac',)], 'col_keys': ['position_name'], 'user_query': 'what is the stocks does the client Broadcom have in their funds?'})

In [21]:
query = "what is the stocks does Mariott have in their equity funds?"
result = await sql_workflow.run(query=query)
result

Running step generate_sql_response
Step generate_sql_response produced event StopEvent

Response(response="I found the following stocks held in Marriott's equity funds:  NVDIA Corp, Apple Inc, Amazon.com Inc, Microsoft Corp, AT&T Inc, Bank of America Corp, Alphabet Inc Class A, Walmart Inc, Exxon Mobil Corp, and Intel Corp.\n", source_nodes=[NodeWithScore(node=TextNode(id_='b7d06e72-dcab-4a49-952a-4e54fb5ce2de', embedding=None, metadata={'sql_query': "SELECT T1.position_name FROM fund_detail AS T1 INNER JOIN portfolio AS T2 ON T1.fund  =  T2.symbol WHERE T2.company ~* '\\yMariott\\y' AND T2.fund_type ~* '\\yEquity Fund\\y'", 'result': [('NVDIA Corp',), ('Apple Inc',), ('Amazon.com Inc',), ('Microsoft Corp',), ('AT&T Inc',), ('Bank fo America Corp',), ('Alphabet Inc Class A',), ('Walmart Inc',), ('Exxon Mobil Corp',), ('Intel Corp',)], 'col_keys': ['position_name']}, excluded_embed_metadata_keys=['sql_query', 'result', 'col_keys'], excluded_llm_metadata_keys=['sql_query', 'result', 'col_keys'], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text="[('NVDIA Corp',), ('Apple Inc',), ('Amazon.com Inc',), ('Microsoft Corp',), ('AT&T Inc',), ('Bank fo America Corp',), ('Alphabet Inc Class A',), ('Walmart Inc',), ('Exxon Mobil Corp',), ('Intel Corp',)]", mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=None)], metadata={'b7d06e72-dcab-4a49-952a-4e54fb5ce2de': {'sql_query': "SELECT T1.position_name FROM fund_detail AS T1 INNER JOIN portfolio AS T2 ON T1.fund  =  T2.symbol WHERE T2.company ~* '\\yMariott\\y' AND T2.fund_type ~* '\\yEquity Fund\\y'", 'result': [('NVDIA Corp',), ('Apple Inc',), ('Amazon.com Inc',), ('Microsoft Corp',), ('AT&T Inc',), ('Bank fo America Corp',), ('Alphabet Inc Class A',), ('Walmart Inc',), ('Exxon Mobil Corp',), ('Intel Corp',)], 'col_keys': ['position_name']}, 'sql_query': "SELECT T1.position_name FROM fund_detail AS T1 INNER JOIN portfolio AS T2 ON T1.fund  =  T2.symbol WHERE T2.company ~* '\\yMariott\\y' AND T2.fund_type ~* '\\yEquity Fund\\y'", 'result': [('NVDIA Corp',), ('Apple Inc',), ('Amazon.com Inc',), ('Microsoft Corp',), ('AT&T Inc',), ('Bank fo America Corp',), ('Alphabet Inc Class A',), ('Walmart Inc',), ('Exxon Mobil Corp',), ('Intel Corp',)], 'col_keys': ['position_name'], 'user_query': 'what is the stocks does Mariott have in their equity funds?'})

In [22]:
query = "What stocks are in the FTIEX equity fund?"
result = await sql_workflow.run(query=query)
result

Running step generate_sql_response
Step generate_sql_response produced event StopEvent

Response(response='The FTIEX equity fund holds the following stocks: Tencent Holdings Ltd, Taiwan Semiconductor Manufacturing, Rheinmetall AG, SAP SE, Samsung Electronics Co Ltd, CRH PLC, BAE Systems PLC, ASML Holding NV, Linde PLC, and Safran SA.\n', source_nodes=[NodeWithScore(node=TextNode(id_='12614861-1c72-4f1f-ab0f-4c415b1216cd', embedding=None, metadata={'sql_query': "SELECT position_name FROM fund_detail WHERE fund ~* '\\yFTIEX\\y';", 'result': [(' Tencent Holdings Ltd',), ('Taiwan Semiconductor Manufacturing',), ('Rheinmetall AG',), ('SAP SE',), ('Samsung Electronics Co Ltd',), ('CRH PLC',), ('BAE Systems PLC',), ('ASML Holding NV',), ('Linde PLC',), ('Safran SA',)], 'col_keys': ['position_name']}, excluded_embed_metadata_keys=['sql_query', 'result', 'col_keys'], excluded_llm_metadata_keys=['sql_query', 'result', 'col_keys'], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text="[(' Tencent Holdings Ltd',), ('Taiwan Semiconductor Manufacturing',), ('Rheinmetall AG',), ('SAP SE',), ('Samsung Electronics Co Ltd',), ('CRH PLC',), ('BAE Systems PLC',), ('ASML Holding NV',), ('Linde PLC',), ('Safran SA',)]", mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=None)], metadata={'12614861-1c72-4f1f-ab0f-4c415b1216cd': {'sql_query': "SELECT position_name FROM fund_detail WHERE fund ~* '\\yFTIEX\\y';", 'result': [(' Tencent Holdings Ltd',), ('Taiwan Semiconductor Manufacturing',), ('Rheinmetall AG',), ('SAP SE',), ('Samsung Electronics Co Ltd',), ('CRH PLC',), ('BAE Systems PLC',), ('ASML Holding NV',), ('Linde PLC',), ('Safran SA',)], 'col_keys': ['position_name']}, 'sql_query': "SELECT position_name FROM fund_detail WHERE fund ~* '\\yFTIEX\\y';", 'result': [(' Tencent Holdings Ltd',), ('Taiwan Semiconductor Manufacturing',), ('Rheinmetall AG',), ('SAP SE',), ('Samsung Electronics Co Ltd',), ('CRH PLC',), ('BAE Systems PLC',), ('ASML Holding NV',), ('Linde PLC',), ('Safran SA',)], 'col_keys': ['position_name'], 'user_query': 'What stocks are in the FTIEX equity fund?'})

In [23]:
query = "What funds does Walmart own? How much money is in each fund?"
result = await sql_workflow.run(query=query)
result

Running step generate_sql_response
Step generate_sql_response produced event StopEvent

Response(response='Walmart appears to own two funds: VSMPX, an Equity Fund with a balance of $15,840,497.97, and TLT, a Bond Fund with a balance of $19,247,911.03.\n', source_nodes=[NodeWithScore(node=TextNode(id_='0a78d8ba-88ab-467d-89a4-8447b0d71eb4', embedding=None, metadata={'sql_query': "SELECT symbol, fund_type, fund_balance FROM portfolio WHERE company ~* '\\yWalmart\\y'", 'result': [('VSMPX', 'Equity Fund', 15840497.97), ('TLT', 'Bond Fund', 19247911.03)], 'col_keys': ['symbol', 'fund_type', 'fund_balance']}, excluded_embed_metadata_keys=['sql_query', 'result', 'col_keys'], excluded_llm_metadata_keys=['sql_query', 'result', 'col_keys'], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text="[('VSMPX', 'Equity Fund', 15840497.97), ('TLT', 'Bond Fund', 19247911.03)]", mimetype='text/plain', start_char_idx=None, end_char_idx=None, metadata_seperator='\n', text_template='{metadata_str}\n\n{content}'), score=None)], metadata={'0a78d8ba-88ab-467d-89a4-8447b0d71eb4': {'sql_query': "SELECT symbol, fund_type, fund_balance FROM portfolio WHERE company ~* '\\yWalmart\\y'", 'result': [('VSMPX', 'Equity Fund', 15840497.97), ('TLT', 'Bond Fund', 19247911.03)], 'col_keys': ['symbol', 'fund_type', 'fund_balance']}, 'sql_query': "SELECT symbol, fund_type, fund_balance FROM portfolio WHERE company ~* '\\yWalmart\\y'", 'result': [('VSMPX', 'Equity Fund', 15840497.97), ('TLT', 'Bond Fund', 19247911.03)], 'col_keys': ['symbol', 'fund_type', 'fund_balance'], 'user_query': 'What funds does Walmart own? How much money is in each fund?'})

# Check Answers accuracy

In [24]:
from google.cloud import secretmanager
import pandas as pd
import numpy as np
from currensee.utils.db_utils import create_pg_engine
from sqlalchemy import text

In [25]:
DB_NAME = 'crm'
engine = create_pg_engine(
   db_name=DB_NAME
)

In [26]:
pd.read_sql("SELECT count(*) FROM Employees", con=engine)

   count
0    100

In [27]:
pd.read_sql("SELECT * FROM portfolio where Company = 'Mariott' ", con=engine)

,account_id,company,symbol,fund_type,tot_balance,fund_balance
0,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,VSMPX,Equity Fund,19512480,12314151.68
1,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,BND,Bond Fund,19512480,7198328.32

In [28]:
pd.read_sql("SELECT * FROM portfolio where Company = 'Broadcom' ", con=engine)

,account_id,company,symbol,fund_type,tot_balance,fund_balance
0,72f9a83c-da3e-4c56-9827-8100a0b8f1a7,Broadcom,VSMPX,Equity Fund,43751152,8189630.80
1,72f9a83c-da3e-4c56-9827-8100a0b8f1a7,Broadcom,FXAIX,Equity Fund,43751152,14499284.22
2,72f9a83c-da3e-4c56-9827-8100a0b8f1a7,Broadcom,FCNTX,Equity Fund,43751152,8895555.38
3,72f9a83c-da3e-4c56-9827-8100a0b8f1a7,Broadcom,MBB,Bond Fund,43751152,3928543.30
4,72f9a83c-da3e-4c56-9827-8100a0b8f1a7,Broadcom,VCSH,Bond Fund,43751152,8238138.30

In [29]:
pd.read_sql("SELECT * FROM client_alignment where Company = 'Mariott' ", con=engine)

,employee_id,employee_first_name,employee_last_name,account_id,company,industry,contact_first_name,contact_last_name,contact_email,contact_title,contact_phone
0,347e2733-4deb-4e98-abcf-c61d76d78bc1,Gary,Jackson,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,Hospitality,Christian,Scott,christian.scott@mariott.com,Consultant,2862521828
1,2e7bc12b-90ac-4df4-b26a-facc0adcc6fe,Vicki,Garner,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,Hospitality,Christian,Scott,christian.scott@mariott.com,Consultant,2862521828
2,fec27a65-3310-4128-a6e2-50ee95c06017,Caleb,Montgomery,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,Hospitality,Christian,Scott,christian.scott@mariott.com,Consultant,2862521828
3,bc4852e0-07a8-4385-bd04-6f260314efeb,James,Gordon,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,Hospitality,Christian,Scott,christian.scott@mariott.com,Consultant,2862521828
4,d12057b4-db73-4731-9392-7b7d71ae9d04,Lisa,Bridges,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,Hospitality,Christian,Scott,christian.scott@mariott.com,Consultant,2862521828
5,34bd865c-8cb1-4f89-b22c-ca8d9c3d3da8,Ashlee,Torres,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,Hospitality,Christian,Scott,christian.scott@mariott.com,Consultant,2862521828
6,56701fd6-5ada-4273-8d70-86946ea3ef3c,Traci,Jacobs,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,Hospitality,Christian,Scott,christian.scott@mariott.com,Consultant,2862521828
7,b82962cd-ca42-4427-9c91-77f6b4c25cb8,Debra,Mendoza,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,Hospitality,Christian,Scott,christian.scott@mariott.com,Consultant,2862521828
8,1a47bc5f-9ecc-4fff-91f8-4b51dbd16a88,Jennifer,Richmond,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,Hospitality,Christian,Scott,christian.scott@mariott.com,Consultant,2862521828
9,c6bf28f1-cdda-402c-b1f0-1ccf14323f99,Donna,Pruitt,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,Hospitality,Christian,Scott,christian.scott@mariott.com,Consultant,2862521828
10,eb0e495a-2b81-45e2-94dc-c79b1dbd7799,Derek,Taylor,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,Hospitality,Christian,Scott,christian.scott@mariott.com,Consultant,2862521828
11,7be9c5f0-e544-4d4b-9a49-722e0a6c0025,Michael,Perez,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,Hospitality,Christian,Scott,christian.scott@mariott.com,Consultant,2862521828
12,104f5b03-0af0-426a-a35d-6569271aa906,Jon,Stanley,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,Hospitality,Christian,Scott,christian.scott@mariott.com,Consultant,2862521828
13,0a3048fa-39cb-4ceb-8347-a0950f044fd5,Ryan,Barnett,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,Hospitality,Christian,Scott,christian.scott@mariott.com,Consultant,2862521828
14,9b75b4fc-2781-43cb-ab18-1ae83b51c51f,Carol,Kelley,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,Hospitality,Christian,Scott,christian.scott@mariott.com,Consultant,2862521828
15,ccef9e84-6357-4d24-9007-bf8ec7bd79e9,Eric,Graves,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,Hospitality,Christian,Scott,christian.scott@mariott.com,Consultant,2862521828
16,4ee1e6f8-b396-4853-8432-8d667e01cb0b,John,Miller,d02ccad1-26c4-4768-95a4-833dbc2b2460,Mariott,Hospitality,Christian,Scott,christian.scott@mariott.com,Consultant,2862521828

In [30]:
pd.read_sql("SELECT * FROM clients_contact where Company = 'Mariott' ", con=engine)

,company,industry,account_id,contact_first_name,contact_last_name,contact_title,phone,email,website,location,annual_revenue,total_account_bal
0,Mariott,Hospitality,d02ccad1-26c4-4768-95a4-833dbc2b2460,Christian,Scott,Consultant,2862521828,christian.scott@mariott.com,http://cohen.com/,Seattle,6924799,19512480

In [31]:
pd.read_sql("""SELECT T1.position_name 
FROM fund_detail AS T1 
JOIN portfolio AS T2 ON 
T1.fund  =  T2.symbol 
WHERE T2.company = 'Mariott' AND T2.fund_type = 'Equity Fund'
""", con = engine)

"""I found the following stocks held in Marriott's equity funds:  NVDIA Corp, Apple Inc, Amazon.com Inc, 
Microsoft Corp, AT&T Inc, Bank of America Corp, Alphabet Inc Class A, Walmart Inc, Exxon Mobil Corp, and Intel Corp"""

"I found the following stocks held in Marriott's equity funds:  NVDIA Corp, Apple Inc, Amazon.com Inc, \nMicrosoft Corp, AT&T Inc, Bank of America Corp, Alphabet Inc Class A, Walmart Inc, Exxon Mobil Corp, and Intel Corp"